---
micronaut:
  application:
    name: account-management
    
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**
        
        
    
    
  server:
    port: 11001

---
tracing:
  zipkin:
    enabled: true
    http:
      url: http://${ZIPKIN_HOST:localhost}:${ZIPKIN_PORT:9411}
    sampler:
      probability: 0.1
---

datasources:
  default:
    url: jdbc:h2:mem:devDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password: ''    
jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update


---
eureka:
  client:
    registration:
      enabled: true
    defaultZone: "${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}"

---
micronaut:
  metrics:
    enabled: true
    export:
      prometheus:
        enabled: true
        step: PT1M
        descriptions: true

---
hystrix:
  stream:
    enabled: false



---
redis:
  uri: redis://${REDIS_HOST:localhost}
